# Generated by Django 3.2.18 on 2023-05-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='renda',
        ),
    ]
