# Generated by Django 3.2.18 on 2023-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_remove_carteira_renda'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='tipo_renda',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='fixa', max_length=30),
            preserve_default=False,
        ),
    ]
