# Generated by Django 3.2.18 on 2023-05-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_carteira_tipo_renda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='tipo_renda',
        ),
    ]
