# Generated by Django 3.2.18 on 2023-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='salario',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
